#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


first_number = 1
second_number = 1

sum = 0

while True:
  new_fib = first_number + second_number
  #Check if number less than max
  if new_fib >= 4000000:
	break
  
  if new_fib % 2 == 0:
    sum += new_fib
  first_number = second_number
  second_number = new_fib
  
print sum
